fixup! qa: Install libpam debug symbols

diff --git a/.github/workflows/qa.yaml b/.github/workflows/qa.yaml
--- a/.github/workflows/qa.yaml
+++ b/.github/workflows/qa.yaml
@@ -85,13 +85,15 @@ jobs:
           sudo apt install -y ${{ env.apt_deps }} ${{ env.protobuf_compilers}} ${{ env.test_apt_deps }}
       - name: Install PAM debug symbols
         run: |
+          set -eu
           sudo apt-get install ubuntu-dbgsym-keyring -y
           echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse
           deb http://ddebs.ubuntu.com $(lsb_release -cs)-updates main restricted universe multiverse
           deb http://ddebs.ubuntu.com $(lsb_release -cs)-proposed main restricted universe multiverse" | \
           sudo tee -a /etc/apt/sources.list.d/ddebs.list
-          sudo apt update -y
-          sudo apt install -y libpam-modules-dbgsym libpam0*-dbgsym
+          # Sometimes ddebs archive is stuck, so in case of failure we ignore this step, it's not fundamental.
+          sudo apt update -y || true
+          sudo apt install -y libpam-modules-dbgsym libpam0*-dbgsym || true
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
